language: java
jdk:
  - openjdk14

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - astolbin@ya.ru
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="723bceba-6428-4f3a-bb52-423f7e3ad68d"